
# The plugin saves the blocks mined data to file every x amount of minutes. Default is 30.
# It also saves the data on disable and loads it on enable.
# This value is in minutes. Set to 0 to disable.
saveInterval: 30

# The span of weekday for displaying weekly blocks mined data.
# Default is weekBegin: "Sunday" & weekEnd: "Saturday"
weekBegin: "Sunday"
weekEnd: "Saturday"

# The top x of gangs to report when using /gtop report.
reportCount: 3

# The amount of MONTHS each gang will have its data saved.
# Note: If you lower this value, you will lose data from older months.
dataSavingLength: 2